=pod

=head1 NAME

Lorem - A tool for the identification, annotation and visualisation of extreme changes in splicing in RNA-seq experiments

=head1 VERSION

lorem 1.0

=head1 SYNOPSIS

lorem [options]

=head1 OPTIONS

=over 8

=item B<--help> | B<-h>

Print the documentation.

=item B<** REQUIRED **>

=item B<--tool> | B<-t> <get_data|get_switch>

Tool to be executed. More information about a specific tool can be obtained
in its help page:

lorem -t get_data -h

=back

=cut
